<a href="https://colab.research.google.com/github/Febriyanto9/Febriyanto/blob/main/UASNO1B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#dataset
JenisKelamin=['Laki-Laki','Laki-Laki','Perempuan','Perempuan','Laki-Laki','Laki-Laki','Perempuan','Perempuan','Laki-Laki','Perempuan']
BiayaPerjalanan=['Murah','Murah','Murah','Murah','Murah','Standar','Standar','Mahal','Mahal','Mahal']
IncomeLevel=['Rendah','Sedang','Sedang','Rendah','Sedang','Sedang','Sedang','Tinggi','Sedang','Tinggi']
ModelTransportasi=['Bus','Bus','Kereta Api','Bus','Bus','Kereta Api','Kereta Api','Mobil','Mobil','Mobil']
Tujuan=['No','Yes','Yes','No','Yes','No','Yes','Yes','No','No']

In [2]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
JenisKelamin_encoded=le.fit_transform(JenisKelamin)
print (JenisKelamin_encoded)

[0 0 1 1 0 0 1 1 0 1]


In [6]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
BiayaPerjalanan_encoded=label.fit_transform(BiayaPerjalanan)
print (BiayaPerjalanan_encoded) 

IncomeLevel_encoded=label.fit_transform(IncomeLevel)
print (IncomeLevel_encoded)

ModelTransportasi_encoded=label.fit_transform(ModelTransportasi)
print (ModelTransportasi_encoded)

Tujuan_encoded=label.fit_transform(Tujuan)
print (Tujuan_encoded)

[1 1 1 1 1 2 2 0 0 0]
[0 1 1 0 1 1 1 2 1 2]
[0 0 1 0 0 1 1 2 2 2]
[0 1 1 0 1 0 1 1 0 0]


In [7]:
print("Jenis Kelamin            :",JenisKelamin_encoded)
print("Biaya Perjalanan(Rp)/km  :",BiayaPerjalanan_encoded)
print("Income Level             :",IncomeLevel_encoded)
print("ModelTransportasi        :",ModelTransportasi_encoded)
print("Tujuan                   :",Tujuan_encoded)#class

Jenis Kelamin            : [0 0 1 1 0 0 1 1 0 1]
Biaya Perjalanan(Rp)/km  : [1 1 1 1 1 2 2 0 0 0]
Income Level             : [0 1 1 0 1 1 1 2 1 2]
ModelTransportasi        : [0 0 1 0 0 1 1 2 2 2]
Tujuan                   : [0 1 1 0 1 0 1 1 0 0]


In [8]:
features=zip(JenisKelamin_encoded,BiayaPerjalanan_encoded,IncomeLevel_encoded,ModelTransportasi_encoded)
features=list(features)
print (tuple(features))

((0, 1, 0, 0), (0, 1, 1, 0), (1, 1, 1, 1), (1, 1, 0, 0), (0, 1, 1, 0), (0, 2, 1, 1), (1, 2, 1, 1), (1, 0, 2, 2), (0, 0, 1, 2), (1, 0, 2, 2))


In [11]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,Tujuan)
#Model.fit(features,label.reshape(-1,1))

#Peridiction Output
predicted = model.predict([[1,2,0,0]]) #1 : perempuan, 2: Standar, 0: Rendah , 0 : Bus
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['No']
